# Generated by Django 3.2.6 on 2021-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(null=True)),
                ('phone_contact', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
